### PR TITLE
Cosmetic changes

### PR DESCRIPTION
**Pull request by mmaruniak**
mrproper

### CODE REVIEW

**Comment by istanishev** [comment]
:)

**Comment by mmaruniak** [comment]
"Only those with write access to this repository can merge pull requests." So (un)fortunately, i can't (or don't have to :) ) do anything about that.

**Comment by istanishev** [comment]
You shouldn't merge, you need to update your pull-request and make it buildable ;)

**Comment by jlaire** [comment]
Making the code readable on GitHub is very good.

Rebase on top of master, then push with --force. Or just merge master to this. Which flow do we prefer?

**Pull request merged**
