### PR TITLE
* Refactoring the specific postal codes class template by moving methods...

### PR DESCRIPTION
**Pull request by istanishev**
... into the base class.

* Fixing small bugs
* Adding more unit tests

### CODE REVIEW

**Comment by rnowosielski** [comment]
I think it looks good :+1:

**Comment by rnowosielski** [comment]
Let's wait for success from AppVeyor, and then I will merge it.

**Comment by istanishev** [comment]
Cool :)

**Comment by jlaire** [comment]
Awesome :)

**Pull request merged**
